export declare function useTable(service?: any): {
    loading: import("vue").Ref<boolean, boolean>;
    data: import("vue").ComputedRef<any>;
    params: import("vue").Ref<any, any>;
    search: () => void;
    reset: () => void;
    refresh: () => void;
    run: () => void;
    onAdd: () => Promise<void>;
    onEdit: (row: any) => Promise<void>;
    onDelete: (row: any) => Promise<void>;
    pageProps: import("vue").Ref<{
        totalKey?: string;
        pageSizeKey?: string;
        currentPageKey?: string;
        small?: boolean;
        disabled?: boolean;
        layout: string;
        background: boolean;
        popperClass?: string;
        teleported?: boolean;
        pagerCount?: number;
        pageSizes?: number[];
        prevText?: string;
        nextText?: string;
        hideOnSinglePage: boolean;
        size?: "" | "default" | "small" | "large";
        currentPage?: number;
        pageCount?: number;
        total?: number;
        pageSize?: number;
        defaultPageSize?: number;
        defaultCurrentPage?: number;
        prevIcon?: any;
        nextIcon?: any;
        appendSizeTo?: string;
    }, {
        totalKey?: string;
        pageSizeKey?: string;
        currentPageKey?: string;
        small?: boolean;
        disabled?: boolean;
        layout: string;
        background: boolean;
        popperClass?: string;
        teleported?: boolean;
        pagerCount?: number;
        pageSizes?: number[];
        prevText?: string;
        nextText?: string;
        hideOnSinglePage: boolean;
        size?: "" | "default" | "small" | "large";
        currentPage?: number;
        pageCount?: number;
        total?: number;
        pageSize?: number;
        defaultPageSize?: number;
        defaultCurrentPage?: number;
        prevIcon?: any;
        nextIcon?: any;
        appendSizeTo?: string;
    } | {
        totalKey?: string;
        pageSizeKey?: string;
        currentPageKey?: string;
        small?: boolean;
        disabled?: boolean;
        layout: string;
        background: boolean;
        popperClass?: string;
        teleported?: boolean;
        pagerCount?: number;
        pageSizes?: number[];
        prevText?: string;
        nextText?: string;
        hideOnSinglePage: boolean;
        size?: "" | "default" | "small" | "large";
        currentPage?: number;
        pageCount?: number;
        total?: number;
        pageSize?: number;
        defaultPageSize?: number;
        defaultCurrentPage?: number;
        prevIcon?: any;
        nextIcon?: any;
        appendSizeTo?: string;
    }>;
    currentPage: import("vue").Ref<any, any>;
    pageSize: import("vue").Ref<any, any>;
};
